### ISSUE TITLE
Wiki - SPT Base Types - Inheritance direction in diagram is wrong?

### ISSUE THREAD

**Issue by stefanspiegel** [Beckhoff-USA-Community/SPT-Libraries#10]
![SPT Base Types Wiki Class Diagramm is wrong](https://user-images.githubusercontent.com/2056117/233958448-3bd4a04a-22ad-4d8c-833c-abc61dc91669.jpg)

**Comment by nshiggins** [comment]
Thanks you are right will get this corrected.

**Comment by MarkLewis-Beckhoff** [comment]
this has been corrected
