### ISSUE TITLE
Make FB_XTS_Mover Inheritable

### ISSUE THREAD

**Issue by bseater** [Beckhoff-USA-Community/SPT-Libraries#14]
Can FB_XTS_Mover have the INTERNAL modifier removed? The use case is adding an additional project specific structure for tracking status of the parts on the mover, where each station can update the status structure as it completes it's processes.  Thanks!

**Comment by nshiggins** [comment]
We can, but the next problem I think you'll have is that the instantiations of FB_XTS_Mover are internal to the XPU component, so I don't think extending would help unless you have some plan that I'm missing.

It's not advertised, but all of the libs in the repo are .library files, so you can add them as an existing file to the PLC node in a solution and then save it off as your own version modifying to suit your specific needs.

In the future I will provide a property where you can plug in your own mover FBs but for now new features are pretty much frozen for the next release.
