### ISSUE TITLE
Difference between SPT-Libraries and PML_Base_Library

### ISSUE THREAD

**Issue by vanoo1983** [Beckhoff-USA-Community/SPT-Libraries#2]
Hello

This is not an issues, this is only a question. What are the differences between the SPT-Libraries and the PML_Base_Library? It seems that only the naming is different?

The same with PackML_PLC/HMI_Example and PML_Base_PLC/HMI. What is the idea behind these projects?

I am working on a new project where I will use PackML and I found these great examples. But now I am not sure which of your projects I should use to get started.

**Comment by nshiggins** [comment]
The PML_Base_** projects are no longer being maintained.  The PackML_** projects (which reference libraries contained within SPT-Libraries repo) are under continuous development.

The primary difference is that the previous libraries extended the PackML state machine into the component (i.e. control module) level.  The new approach is to NOT do this--components can be used standalone without any knowledge of PackML.  We felt this approach allowed more flexibility to use pre-built components in non-PackML projects.  There are a few optimizations to the PackML layer as well--it was basically a line-by-line review so it will look familiar if you used the previous iteration.
