### ISSUE TITLE
Sensor HardwareInput how to assign?

### ISSUE THREAD

**Issue by runtimevic** [Beckhoff-USA-Community/SPT-Libraries#21]
Hello,
Sensor HardwareInput how to assign?
attached image...
<img width="1021" alt="SPT Application Framework_Sensor" src="https://github.com/Beckhoff-USA-Community/SPT-Libraries/assets/53791834/41d96b4d-759b-4669-ba07-4f667c3d5c7b">

**Comment by nshiggins** [comment]
HardwareInput is meant to be linked directly to hardware (AT %I*)
