### ISSUE TITLE
Space added in component name

### ISSUE THREAD

**Issue by MrKirkegaard** [Beckhoff-USA-Community/SPT-Libraries#23]
The logic in FB_PackML_BaseModule.Initialize addes an extra space in the commponent names.

The Component name is "_**GL1.GL1.GMD1-YS1**_" according to ISO/IEC 81346, but in the SPT framework the component gets the name "**_GL1.GL1 .GMD1-YS1_**"

![image](https://github.com/Beckhoff-USA-Community/SPT-Libraries/assets/9883540/380b3744-86b6-4c87-8c84-c1bcee2f2466)

**Comment by nshiggins** [comment]
Thanks will add to work items and update soon.  This could be a breaking change depending on existing HMI applications so will likely introduce a library parameter where user can specify delimiter.

**Comment by MrKirkegaard** [comment]
Thank you.
Can the same type of name concatenation be added to the ipSubModules array, by means of a library parameter?

**Comment by nshiggins** [comment]
This has been addressed and released in SPT_Base_Types v3.2.4
