### ISSUE TITLE
SPT component base reference error

### ISSUE THREAD

**Issue by baseljaber** [Beckhoff-USA-Community/SPT-Libraries#26]
the library **SPT component base** is referencing **tc3_system**, which does not exist, I guess it should reference **tc2_system**

Best regards
Basel Jaber

**Comment by nshiggins** [comment]
Can you show me where this is the case?  This issue was addressed in v3.1.1:  https://beckhoff-usa-community.github.io/SPT-Libraries/SPT_Components/changelog.html

**Comment by baseljaber** [comment]
You can see it when the library is referenced in Twincat: 

![image](https://github.com/Beckhoff-USA-Community/SPT-Libraries/assets/32358868/09bfc326-5e82-4a00-a5b2-59488462c48d)

and when you open the dependencies file:

![image](https://github.com/Beckhoff-USA-Community/SPT-Libraries/assets/32358868/ca4f8d59-cce5-4046-a55a-a8ac94ccbf2c)

and it throws an error when compiling the project:

![image](https://github.com/Beckhoff-USA-Community/SPT-Libraries/assets/32358868/048868fd-3612-40bb-b733-a8a29a3502bd)

**Comment by nshiggins** [comment]
SPT Component Types library has been deprecated.  That code now lives in the SPT Base Types library.
