### ISSUE TITLE
DigitalSensor configuration overwritten if HMI control is available.

### ISSUE THREAD

**Issue by MrKirkegaard** [Beckhoff-USA-Community/SPT-Libraries#27]
The data structure DigitalSensor_HMI.Config is never initialized, like in other components like FB_SingleSolenoid.
![image](https://github.com/Beckhoff-USA-Community/SPT-Libraries/assets/9883540/8db39499-ae22-4bb3-913d-10021394b60b)
Any configured values are overwritten with the initial values from DigitalSensor_HMI.Config, when HMI control becomes available. Any signal inversion configured during module initialization is reset in manual mode.

**Comment by nshiggins** [comment]
Thanks--fixed and pending release
