### ISSUE TITLE
FB_SingleSolenoid.Reset() never return true

### ISSUE THREAD

**Issue by MrKirkegaard** [Beckhoff-USA-Community/SPT-Libraries#29]
The Reset method never returns true, and does not call Reset() of the component base.
![image](https://github.com/Beckhoff-USA-Community/SPT-Libraries/assets/9883540/c72d6d59-f79d-48b6-950b-c798b5701995)

**Comment by KeithBaker123** [comment]
Hello Mr Kirkegarrd - This issue has been fixed and will be rolled out in next version.

Thank you for helping us make it better.
