### ISSUE TITLE
I_DigitalSensorBase no `Active` Property

### ISSUE THREAD

**Issue by kaelev7** [Beckhoff-USA-Community/SPT-Libraries#31]
Is there any reason that the Interface `I_DigitalSensorBase` has no `Active` property, but the implementation `FB_DigitalSensor` has?   
   
Library version is 3.2.3. 

I can't see in the library manager, nor if I create an instance of  `I_DigitalSensorBase` and try to access it.

**Comment by nshiggins** [comment]
Thanks--fixed in upcoming release
