### ISSUE TITLE
SPT_Component_Base contains Tc3_System

### ISSUE THREAD

**Issue by BABE-KimR** [Beckhoff-USA-Community/SPT-Libraries#33]
SPT_Component_Base 3.0.2 contains a reference to Tc3_System.lib which is not necessary and is not part of the standard TwinCAT 4024 XAE install

**Comment by MarkLewis-Beckhoff** [comment]
This reference was eliminated in more recent builds. please make sure you are using the latest library builds and pull new builds if needed.
![image](https://github.com/Beckhoff-USA-Community/SPT-Libraries/assets/53493185/313f45b9-1be6-446f-816c-35421a57fa2a)
