### ISSUE TITLE
Tracing: AddWithJson / AddEntryWithJson

### ISSUE THREAD

**Issue by stefanspiegel** [Beckhoff-USA-Community/SPT-Libraries#4]
Hi all,

I have updated to SPT_Base_Types V3.0.1. The Function Block FB_BaseFB no calls a Method xxx.AddWithJson. This is not compiling.
Shouldn't it be xxx.Add**Entry**WithJson?

Thanks for your answer.

Best regards, Stefan

**Comment by nshiggins** [comment]
Thanks Stefan I thought I fixed this yesterday--is it still an issue?

**Comment by MarkLewis-Beckhoff** [comment]
Forgot the () ?

Sent from Nine<http://www.9folders.com/>
________________________________

**Comment by nshiggins** [comment]
No--the Trace() and TraceWithJson() methods in FB_BaseFB are just wrappers for the global tracing FB that is in SPT_Tracing library.   
 They call the global AddEntry() and AddEntryWithJson() and pass in the caller's FB instance name, etc.  The JSON stuff was a last minute addition and I changed the SPT_Tracing method name (was AddWithJson() --> AddEntryWithJson()) right before committing the libraries and didn't change the wrapper method.  Too excited to get it off my plate--my mistake.
