### ISSUE TITLE
MM or EM custom HMI Communication

### ISSUE THREAD

**Issue by 99jj234** [Beckhoff-USA-Community/SPT-Libraries#50]
HMI patterns for components are well documented. No problems there.

But what are the recommendations for Equipment Module or Machine Module HMI communication? Documentation for that either does not exist yet, or I suck at finding it.

AB#4650

**Comment by nshiggins** [comment]
Apologies for delayed response...busy times to be sure.

For descendants of FB_PackML_BaseModule the pattern should be more or less the same as components.  There is a method HMICommunication that is called cyclically, and a group of structs underneath ST_PackMLBaseModule_HMI that allow for basic commands like changing modes, commanding state changes, etc.

For application-specific stuff, override the HMICommunication method (or just copy/paste from the base) and make your own struct/variables/whatever.  Make a call to SUPER^.HMICommunication() to preserve the base functionality.
