### ISSUE TITLE
Very minor typing issue

### ISSUE THREAD

**Issue by stefanspiegel** [Beckhoff-USA-Community/SPT-Libraries#51]
In the comment for the FB_DigitalSensor - HardwareInput is a "p" missing :-) The comment is shown, when mapping to real hardware.

FUNCTION_BLOCK FB_DigitalSensor EXTENDS FB_ComponentBase IMPLEMENTS I_DigitalSensorBase
VAR
	HardwareInput AT %I*		: BOOL;			  //Hardware input bit from the **hysical** sensor

AB#4682

**Comment by nshiggins** [comment]
:) staged for next release

![image](https://github.com/Beckhoff-USA-Community/SPT-Libraries/assets/18381949/86781e00-480d-4e9a-a980-813c3882605f)
