### ISSUE TITLE
General HMI to PLC interface design

### ISSUE THREAD

**Issue by micfonon** [Beckhoff-USA-Community/SPT-Libraries#52]
With the PackML interface, it's only possible to control the PackML state either by using a control source or accessing the PackMLBaseModule_HMI.Command variable.

two questions:
* should I use PackMLBaseModule_HMI or always use the controlSource?
* how to implement product specific interfaces?  I know I can just write my own interface and handle it myself, but is this in the spirit of the SPT framework? Surely not everything can be controlled by PackML state triggers?

AB#4689

**Comment by nshiggins** [comment]
ControlSource was originally intended as a way to handle simple things like pushbutton clusters (think Start/Stop/Reset buttons).  The ***_HMI structures are there for....HMIs....or for that matter anything that can reach in via ADS (or OPC, but that would require use of unfiltered symbols at the moment).

I'm not 100% clear on point 2 above.  I would guess that the answer may be that for product specific logic, override CyclicLogic (or any of the existing methods that are automatically called for you) and make it your machine.  Make a SUPER^ call to the method you overrode to preserve existing behaviors.
