### ISSUE TITLE
TC3.1 V4024.56, Libs don't work

### ISSUE THREAD

**Issue by andreasso-Beckhoff** [Beckhoff-USA-Community/SPT-Libraries#56]
Solved! There where newer libs missing.

I installed all the libs from the demo project.
I'm getting these errors :
File	Severity	Code	Description	Project	Line	Suppression State
PLC1.Library Manager	Error		Could not open library '#SPT Base Types'. (Reason: The library 'SPT Base Types, 3.2.9.1 (Beckhoff Automation LLC)' has not been installed to the system.)	PLC1	0	
PLC1.Library Manager	Error		Could not open library '#SPT Components'. (Reason: The library 'SPT Components, 3.2.6.1 (Beckhoff Automation LLC)' has not been installed to the system.)	PLC1	0	
PLC1.Library Manager	Error		Could not open library '#SPT Utilities'. (Reason: The library 'SPT Utilities, 3.2.2 (Beckhoff Automation LLC)' has not been installed to the system.)	PLC1	0	

Once i double klick on the error, XAE closes and reopens.

Regards,

Andreas

AB#4764

**Comment by mcclureTC** [comment]
@andreasso-Beckhoff, please check this link for details to install the SPT_Framework libraries as they are not contained within the repo for the VFFS demo. https://github.com/Beckhoff-USA-Community/SPT-Libraries

Also, there are some videos here that you might find useful: https://beckhoff-usa-community.github.io/SPT-Libraries/Getting_Started/Videos.html
