### ISSUE TITLE
TC3_system in NC_Homing

### ISSUE THREAD

**Issue by albertgoodwin** [Beckhoff-USA-Community/SPT-Libraries#62]
<img width="1165" alt="image" src="https://github.com/Beckhoff-USA-Community/SPT-Libraries/assets/103585550/080b4372-9562-4cce-b60c-cf02624238b9">

i still see TC3_system as a dependency in NC_Homing, which is causing build fails. What am i missing?

_Originally posted by @albertgoodwin in https://github.com/Beckhoff-USA-Community/SPT-Libraries/issues/41#issuecomment-2189089557_
            

AB#4960

**Comment by nshiggins** [comment]
That particular library was deprecated in april of 2022.  The contents were merged into the SPT_MotionControl library, which does not have this dependency.

https://beckhoff-usa-community.github.io/SPT-Libraries/SPT_MotionControl/changelog.html#added_3
