### ISSUE TITLE
When NCI reset fails, clearing will retry too many times

### ISSUE THREAD

**Issue by micfonon** [Beckhoff-USA-Community/SPT-Libraries#73]
For a  (yet unknown) reason, my NC module Interpreter State is stuck at init failed (in TC 4026).

That is a separate issue, but:
- In FB_Component_NciBase.Monitoring an alarm is raised because of this (fine of course).
- In an SubModule that own the SPT NCI component in FB_PackML_BaseModule.Clearing, it will:
  
FOR i := 1 TO NumberOfComponents DO
    IF Parameters_PackML_Base.RESET_COMPONENTS_WITHOUT_ERROR THEN
    ipComponents[i].Reset();
      ELSE
        IF ipComponents[i].Error THEN
        ipComponents[i].Reset();
      END_IF
    END_IF
  END_FOR

- The Reset method of Nci is called again, and it will Clear the event
- but if the Error remains, it will retry 1000 of times, causing 1000s of Raising/Clearing events

Is this proper behaviour? I would  think if reset fails, don't try again, or let the user decide to retry.
(Or do I do something wrong).

AB#5505

**Comment by FlorianSiBeckhoff** [comment]
In case the Clearing() is not overwritten, the state is complete in one cycle. That will transition the state machine to stopped, however the following cycle will allow the error reaction to abort the state machine again.

In case your Clearing() has more than one step or another component which does not clear in one cycle, the error will be raised and cleared again as we block the abort mechanism during clearing. This is necessary to be able to clear any error.

If you expect errors to re-appear during clearing, I recommend a retry mechanism. 
After retrying fails you can call Super^.ChangeState() to abort and remain in aborted state with the error raised to do further debugging.
