### ISSUE TITLE
SPT libraries available as TCPKG feed?

### ISSUE THREAD

**Issue by albertgoodwin** [Beckhoff-USA-Community/SPT-Libraries#82]
i see some new developments in the repository that look like you are delivering these libraries to a TCPkg feed somewhere. Is that available to play with yet?

AB#6151

**Comment by iadonkey** [comment]
Check https://github.com/Beckhoff-USA-Community/SPT-Libraries/blob/main/TcPkg-Build/PackagePusher.ps1
Looks like the libraries are uploaded to https://community.beckhoff-usa.com, but I guess you'll not get their private key :D

**Comment by iadonkey** [comment]
@0w8States, if you have an offical release, is adding the library to [Twinpack](https://github.com/zeugwerk/twinpack-registry) an option for you?

**Comment by 0w8States** [comment]
@iadonkey At this time we are not supporting an official public facing package feed for these community packages. We have tested and do have a feed on standby for poential future release. At the moment, we've left it to the user to compile them using the custom TcPkg package template, and they can then self host on their hard disk or via NuGet package server such as Nexus or Nuget.Server.

For packages that are not hosted on a official Beckhoff Germany source, the TcPkg package signing check needs to be disabled with the TcPkg command line utility. This is left to the user to decide for security reasons, as it could allow for any packages to be installed freely on a system; both signed and unsigned.
